//! Distributed Lock Manager calls and native request fields/constants.
//!
//! Prepare a UBF with [`AtmiCtx::tpdlmmkcall`], then use the generated service
//! name with a DLM call. Native retry and timeout policy belongs to Enduro/X.
//! The DLM service requires an Enduro/X installation providing `tpdlmsv`.
// Native long widths vary by target.
#![allow(clippy::unnecessary_cast)]
use crate::{raw, AtmiCtx, AtmiError, AtmiResult, TypedBuffer, TypedUbf};
use std::ffi::CString;
use std::os::raw::{c_char, c_long};

/// Controls preparation of a native DLM request.
pub struct TpDlmCtl {
    inner: raw::TPDLMCTL,
}

impl Default for TpDlmCtl {
    fn default() -> Self {
        Self {
            inner: unsafe { std::mem::zeroed() },
        }
    }
}

impl TpDlmCtl {
    /// Return preparation flags (currently reserved; zero is required).
    pub fn flags(&self) -> i64 {
        self.inner.flags as i64
    }

    /// Set preparation flags. Only zero is supported by the native API.
    pub fn set_flags(&mut self, flags: i64) -> AtmiResult<&mut Self> {
        if flags != 0 {
            return Err(AtmiError::new(
                AtmiError::TPEINVAL,
                "DLM preparation flags must be zero",
            ));
        }
        self.inner.flags = 0;
        Ok(self)
    }

    /// Return the DLM space used to generate the destination service name.
    pub fn dlmspace(&self) -> String {
        crate::fixed_cstr_to_string(&self.inner.dlmspace)
    }

    /// Set the DLM space, rejecting NULs and names beyond the native limit.
    pub fn set_dlmspace(&mut self, space: &str) -> AtmiResult<&mut Self> {
        crate::write_fixed_str(&mut self.inner.dlmspace, space, "dlmspace")?;
        Ok(self)
    }

    /// Return the service name generated by `tpdlmmkcall` or set explicitly.
    pub fn svcname(&self) -> String {
        crate::fixed_cstr_to_string(&self.inner.svcname)
    }

    /// Set an explicit service name. A nonempty DLM space replaces it during preparation.
    pub fn set_svcname(&mut self, service: &str) -> AtmiResult<&mut Self> {
        crate::write_fixed_str(&mut self.inner.svcname, service, "svcname")?;
        Ok(self)
    }

    /// Return the scheduler wait time in milliseconds.
    pub fn wait_time(&self) -> i64 {
        self.inner.wait_time as i64
    }

    /// Set a nonnegative scheduler wait in milliseconds; zero selects the native default.
    pub fn set_wait_time(&mut self, millis: i64) -> AtmiResult<&mut Self> {
        let value = c_long::try_from(millis)
            .map_err(|_| AtmiError::new(AtmiError::TPEINVAL, "DLM wait exceeds native long"))?;
        if value < 0 {
            return Err(AtmiError::new(
                AtmiError::TPEINVAL,
                "DLM wait must be nonnegative",
            ));
        }
        self.inner.wait_time = value;
        Ok(self)
    }
}

/// Native retry budget and per-attempt timeout calculation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TpDlmTimeout {
    /// Total retry budget in milliseconds.
    pub total_millis: i64,
    /// DLM budget for each attempt in milliseconds.
    pub attempt_millis: i64,
    /// XATMI blocking timeout for each attempt in whole seconds.
    pub block_seconds: i64,
}

impl AtmiCtx {
    /// Prepare DLM identities, wait time and sequence fields, growing UBFs as needed.
    ///
    /// `data` owns all nested `EX_DLM_CMDENTRY` targets, which must be non-null
    /// UBF buffers. Shared or cyclic ownership graphs are rejected. This operation
    /// can partially modify the request on failure. Both root and child pointer
    /// changes remain owned by the request. `ctl.svcname()` receives the service
    /// name generated from a nonempty `ctl.dlmspace()`.
    pub fn tpdlmmkcall(&self, data: &mut TypedUbf<'_>, ctl: &mut TpDlmCtl) -> AtmiResult<()> {
        data.ensure_owned_tree()
            .map_err(|e| AtmiError::new(AtmiError::TPEINVAL, e.message))?;
        let count = data
            .ctx()
            .boccur(data, EX_DLM_CMDENTRY)
            .map_err(|e| AtmiError::new(AtmiError::TPEINVAL, e.message))?;
        for occurrence in 0..count {
            data.bget_ptr_ubf(EX_DLM_CMDENTRY, occurrence as i32)
                .map_err(|e| AtmiError::new(AtmiError::TPEINVAL, e.message))?;
        }
        let mut pointer = data.as_ubfh();
        #[cfg(not(feature = "ctx-send"))]
        let rc = unsafe { raw::tpdlmmkcall(&mut pointer, &mut ctl.inner) };
        #[cfg(feature = "ctx-send")]
        let rc = unsafe { raw::Otpdlmmkcall(self.c_ctx_ptr(), &mut pointer, &mut ctl.inner) };
        data.replace_ptr(pointer.cast());
        data.set_len_reported(0);
        self.rc_to_result(rc)
    }

    /// Make a synchronous DLM call using the core retry policy.
    ///
    /// Prepare `idata` with `tpdlmmkcall` first. It is borrowed exclusively because
    /// native retries update wait and sequence fields, including nested commands.
    /// `odata` adopts native pointer and length changes on success and failure.
    /// `TPNOREPLY` is invalid. The native call enforces `TPNOTRAN`.
    pub fn tpdlmcall(
        &self,
        svc: &str,
        idata: &mut TypedUbf<'_>,
        odata: &mut TypedBuffer<'_>,
        flags: i64,
    ) -> AtmiResult<()> {
        let svc = CString::new(svc)
            .map_err(|_| AtmiError::new(AtmiError::TPEINVAL, "DLM service contains NUL"))?;
        idata
            .ensure_owned_tree()
            .map_err(|e| AtmiError::new(AtmiError::TPEINVAL, e.message))?;
        let mut pointer = odata.as_ptr();
        let mut len = c_long::try_from(odata.len())
            .map_err(|_| AtmiError::new(AtmiError::TPEINVAL, "reply length exceeds native long"))?;
        #[cfg(not(feature = "ctx-send"))]
        let rc = unsafe {
            raw::tpdlmcall(
                svc.as_ptr() as *mut c_char,
                idata.as_ptr(),
                0,
                &mut pointer,
                &mut len,
                flags as c_long,
            )
        };
        #[cfg(feature = "ctx-send")]
        let rc = unsafe {
            raw::Otpdlmcall(
                self.c_ctx_ptr(),
                svc.as_ptr() as *mut c_char,
                idata.as_ptr(),
                0,
                &mut pointer,
                &mut len,
                flags as c_long,
            )
        };
        odata.replace_ptr(pointer);
        odata.set_len_reported(len.max(0) as usize);
        self.rc_to_result(rc)
    }

    /// Submit a DLM request with native send retries and return its call descriptor.
    /// Collect the reply with `tpgetrply`. Submission is synchronous and can block;
    /// only submission is retried. The core enforces `TPNOTRAN`.
    pub fn tpdlmacall(&self, svc: &str, data: &TypedUbf<'_>, flags: i64) -> AtmiResult<i32> {
        let svc = CString::new(svc)
            .map_err(|_| AtmiError::new(AtmiError::TPEINVAL, "DLM service contains NUL"))?;
        #[cfg(not(feature = "ctx-send"))]
        let rc = unsafe {
            raw::tpdlmacall(
                svc.as_ptr() as *mut c_char,
                data.as_ptr(),
                0,
                flags as c_long,
            )
        };
        #[cfg(feature = "ctx-send")]
        let rc = unsafe {
            raw::Otpdlmacall(
                self.c_ctx_ptr(),
                svc.as_ptr() as *mut c_char,
                data.as_ptr(),
                0,
                flags as c_long,
            )
        };
        if rc < 0 {
            Err(self.atmi_last_error())
        } else {
            Ok(rc)
        }
    }

    /// Establish a DLM conversation with native retries and return its descriptor.
    /// Subsequent `tpsend`/`tprecv` calls and reconnection belong to the caller.
    /// The core enforces `TPNOTRAN`.
    pub fn tpdlmconnect(&self, svc: &str, data: &TypedUbf<'_>, flags: i64) -> AtmiResult<i32> {
        let svc = CString::new(svc)
            .map_err(|_| AtmiError::new(AtmiError::TPEINVAL, "DLM service contains NUL"))?;
        #[cfg(not(feature = "ctx-send"))]
        let rc = unsafe {
            raw::tpdlmconnect(
                svc.as_ptr() as *mut c_char,
                data.as_ptr(),
                0,
                flags as c_long,
            )
        };
        #[cfg(feature = "ctx-send")]
        let rc = unsafe {
            raw::Otpdlmconnect(
                self.c_ctx_ptr(),
                svc.as_ptr() as *mut c_char,
                data.as_ptr(),
                0,
                flags as c_long,
            )
        };
        if rc < 0 {
            Err(self.atmi_last_error())
        } else {
            Ok(rc)
        }
    }

    /// Calculate native DLM retry timing. Nonpositive waits use the effective XATMI timeout.
    pub fn tpdlmtoutget(&self, wait_millis: i64) -> AtmiResult<TpDlmTimeout> {
        let wait = c_long::try_from(wait_millis)
            .map_err(|_| AtmiError::new(AtmiError::TPEINVAL, "DLM wait exceeds native long"))?;
        let (mut total, mut attempt, mut block) = (0, 0, 0);
        #[cfg(not(feature = "ctx-send"))]
        let rc = unsafe { raw::tpdlmtoutget(wait, &mut total, &mut attempt, &mut block) };
        #[cfg(feature = "ctx-send")]
        let rc = unsafe {
            raw::Otpdlmtoutget(self.c_ctx_ptr(), wait, &mut total, &mut attempt, &mut block)
        };
        self.rc_to_result(rc)?;
        Ok(TpDlmTimeout {
            total_millis: total as i64,
            attempt_millis: attempt as i64,
            block_seconds: block as i64,
        })
    }

    /// Return the configured native DLM attempt count (at least one).
    pub fn tpdlmattemptsget(&self) -> AtmiResult<i32> {
        #[cfg(not(feature = "ctx-send"))]
        let rc = unsafe { raw::tpdlmattemptsget() };
        #[cfg(feature = "ctx-send")]
        let rc = unsafe { raw::Otpdlmattemptsget(self.c_ctx_ptr()) };
        if rc < 0 {
            Err(self.atmi_last_error())
        } else {
            Ok(rc)
        }
    }
}

// Values are taken from the selected native headers.
/// Native `NDRX_DLM_ISLOCKED_NOLOCK` constant.
pub const NDRX_DLM_ISLOCKED_NOLOCK: i64 = raw::NDRX_DLM_ISLOCKED_NOLOCK as i64;
/// Native `NDRX_DLM_ISLOCKED_LKDATA` constant.
pub const NDRX_DLM_ISLOCKED_LKDATA: i64 = raw::NDRX_DLM_ISLOCKED_LKDATA as i64;
/// Native `NDRX_DLM_ISLOCKED_EPRECOND` constant.
pub const NDRX_DLM_ISLOCKED_EPRECOND: i64 = raw::NDRX_DLM_ISLOCKED_EPRECOND as i64;
/// Native `NDRX_DLM_ISLOCKED_LKMATCH` constant.
pub const NDRX_DLM_ISLOCKED_LKMATCH: i64 = raw::NDRX_DLM_ISLOCKED_LKMATCH as i64;
/// Native `NDRX_DLM_ISLOCKED_LKNL` constant.
pub const NDRX_DLM_ISLOCKED_LKNL: i64 = raw::NDRX_DLM_ISLOCKED_LKNL as i64;
/// Native `NDRX_DLM_ISLOCKED_LKCR` constant.
pub const NDRX_DLM_ISLOCKED_LKCR: i64 = raw::NDRX_DLM_ISLOCKED_LKCR as i64;
/// Native `NDRX_DLM_ISLOCKED_LKCW` constant.
pub const NDRX_DLM_ISLOCKED_LKCW: i64 = raw::NDRX_DLM_ISLOCKED_LKCW as i64;
/// Native `NDRX_DLM_ISLOCKED_LKPR` constant.
pub const NDRX_DLM_ISLOCKED_LKPR: i64 = raw::NDRX_DLM_ISLOCKED_LKPR as i64;
/// Native `NDRX_DLM_ISLOCKED_LKPW` constant.
pub const NDRX_DLM_ISLOCKED_LKPW: i64 = raw::NDRX_DLM_ISLOCKED_LKPW as i64;
/// Native `NDRX_DLM_ISLOCKED_LKEX` constant.
pub const NDRX_DLM_ISLOCKED_LKEX: i64 = raw::NDRX_DLM_ISLOCKED_LKEX as i64;
/// Native `NDRX_DLM_ISLOCKED_LKONL` constant.
pub const NDRX_DLM_ISLOCKED_LKONL: i64 = raw::NDRX_DLM_ISLOCKED_LKONL as i64;
/// Native `NDRX_DLM_ISLOCKED_LKOCR` constant.
pub const NDRX_DLM_ISLOCKED_LKOCR: i64 = raw::NDRX_DLM_ISLOCKED_LKOCR as i64;
/// Native `NDRX_DLM_ISLOCKED_LKOCW` constant.
pub const NDRX_DLM_ISLOCKED_LKOCW: i64 = raw::NDRX_DLM_ISLOCKED_LKOCW as i64;
/// Native `NDRX_DLM_ISLOCKED_LKOPR` constant.
pub const NDRX_DLM_ISLOCKED_LKOPR: i64 = raw::NDRX_DLM_ISLOCKED_LKOPR as i64;
/// Native `NDRX_DLM_ISLOCKED_LKOPW` constant.
pub const NDRX_DLM_ISLOCKED_LKOPW: i64 = raw::NDRX_DLM_ISLOCKED_LKOPW as i64;
/// Native `NDRX_DLM_ISLOCKED_LKOEX` constant.
pub const NDRX_DLM_ISLOCKED_LKOEX: i64 = raw::NDRX_DLM_ISLOCKED_LKOEX as i64;
/// Native `NDRX_DLM_FL_FLATUBF` constant.
pub const NDRX_DLM_FL_FLATUBF: i64 = raw::NDRX_DLM_FL_FLATUBF as i64;
/// Native `NDRX_DLM_FL_FLATBLOB` constant.
pub const NDRX_DLM_FL_FLATBLOB: i64 = raw::NDRX_DLM_FL_FLATBLOB as i64;
/// Native `NDRX_DLM_FL_CONVERT` constant.
pub const NDRX_DLM_FL_CONVERT: i64 = raw::NDRX_DLM_FL_CONVERT as i64;
/// Native `NDRX_DLM_FL_MIGRATER` constant.
pub const NDRX_DLM_FL_MIGRATER: i64 = raw::NDRX_DLM_FL_MIGRATER as i64;
/// Native `NDRX_DLM_FL_NOBLOCK` constant.
pub const NDRX_DLM_FL_NOBLOCK: i64 = raw::NDRX_DLM_FL_NOBLOCK as i64;
/// Native `NDRX_DLM_FL_REGEX` constant.
pub const NDRX_DLM_FL_REGEX: i64 = raw::NDRX_DLM_FL_REGEX as i64;
/// Native `NDRX_DLM_FL_NODATA` constant.
pub const NDRX_DLM_FL_NODATA: i64 = raw::NDRX_DLM_FL_NODATA as i64;
/// Native `NDRX_DLM_FL_EXPIRY` constant.
pub const NDRX_DLM_FL_EXPIRY: i64 = raw::NDRX_DLM_FL_EXPIRY as i64;
/// Native `NDRX_DLM_FL_EXPFENCE` constant.
pub const NDRX_DLM_FL_EXPFENCE: i64 = raw::NDRX_DLM_FL_EXPFENCE as i64;
/// Native `NDRX_DLM_FL_EXPEVENT` constant.
pub const NDRX_DLM_FL_EXPEVENT: i64 = raw::NDRX_DLM_FL_EXPEVENT as i64;
/// Native `NDRX_DLM_FL_FENCEEVENT` constant.
pub const NDRX_DLM_FL_FENCEEVENT: i64 = raw::NDRX_DLM_FL_FENCEEVENT as i64;
/// Native `NDRX_DLM_FL_EXPPIDFENCE` constant.
pub const NDRX_DLM_FL_EXPPIDFENCE: i64 = raw::NDRX_DLM_FL_EXPPIDFENCE as i64;
/// Native `NDRX_DLM_FL_LOCALINFO` constant.
pub const NDRX_DLM_FL_LOCALINFO: i64 = raw::NDRX_DLM_FL_LOCALINFO as i64;
/// Native `NDRX_DLM_FL_KEYASCID` constant.
pub const NDRX_DLM_FL_KEYASCID: i64 = raw::NDRX_DLM_FL_KEYASCID as i64;
/// Native `NDRX_DLM_FL_BYPID` constant.
pub const NDRX_DLM_FL_BYPID: i64 = raw::NDRX_DLM_FL_BYPID as i64;
/// Native `NDRX_DLM_FL_NOPIDCHK` constant.
pub const NDRX_DLM_FL_NOPIDCHK: i64 = raw::NDRX_DLM_FL_NOPIDCHK as i64;
/// Native `NDRX_DLM_FL_IGNOWNER` constant.
pub const NDRX_DLM_FL_IGNOWNER: i64 = raw::NDRX_DLM_FL_IGNOWNER as i64;
/// Native `NDRX_DLM_FL_PRECOND` constant.
pub const NDRX_DLM_FL_PRECOND: i64 = raw::NDRX_DLM_FL_PRECOND as i64;
/// Native `NDRX_DLM_FL_LINREAD` constant.
pub const NDRX_DLM_FL_LINREAD: i64 = raw::NDRX_DLM_FL_LINREAD as i64;
/// Native `NDRX_DLM_FL_FORCE` constant.
pub const NDRX_DLM_FL_FORCE: i64 = raw::NDRX_DLM_FL_FORCE as i64;
/// Native `NDRX_DLM_FL_EVFLAT` constant.
pub const NDRX_DLM_FL_EVFLAT: i64 = raw::NDRX_DLM_FL_EVFLAT as i64;
/// Native `NDRX_DLM_FENCE_CODE_BUFSZ` constant.
pub const NDRX_DLM_FENCE_CODE_BUFSZ: i64 = raw::NDRX_DLM_FENCE_CODE_BUFSZ as i64;
/// Native `EX_DLM_CMD` constant.
pub const EX_DLM_CMD: i32 = raw::NDRX_RS_EX_DLM_CMD as i32;
/// Native `EX_DLM_OP` constant.
pub const EX_DLM_OP: i32 = raw::NDRX_RS_EX_DLM_OP as i32;
/// Native `EX_DLM_FLAGS` constant.
pub const EX_DLM_FLAGS: i32 = raw::NDRX_RS_EX_DLM_FLAGS as i32;
/// Native `EX_DLM_KEY` constant.
pub const EX_DLM_KEY: i32 = raw::NDRX_RS_EX_DLM_KEY as i32;
/// Native `EX_DLM_EXPIRY` constant.
pub const EX_DLM_EXPIRY: i32 = raw::NDRX_RS_EX_DLM_EXPIRY as i32;
/// Native `EX_DLM_CID` constant.
pub const EX_DLM_CID: i32 = raw::NDRX_RS_EX_DLM_CID as i32;
/// Native `EX_DLM_DATA` constant.
pub const EX_DLM_DATA: i32 = raw::NDRX_RS_EX_DLM_DATA as i32;
/// Native `EX_DLM_CURDATA` constant.
pub const EX_DLM_CURDATA: i32 = raw::NDRX_RS_EX_DLM_CURDATA as i32;
/// Native `EX_DLM_CMDENTRY` constant.
pub const EX_DLM_CMDENTRY: i32 = raw::NDRX_RS_EX_DLM_CMDENTRY as i32;
/// Native `EX_DLM_PID` constant.
pub const EX_DLM_PID: i32 = raw::NDRX_RS_EX_DLM_PID as i32;
/// Native `EX_DLM_PID_START` constant.
pub const EX_DLM_PID_START: i32 = raw::NDRX_RS_EX_DLM_PID_START as i32;
/// Native `EX_DLM_NODEID` constant.
pub const EX_DLM_NODEID: i32 = raw::NDRX_RS_EX_DLM_NODEID as i32;
/// Native `EX_DLM_REQCID` constant.
pub const EX_DLM_REQCID: i32 = raw::NDRX_RS_EX_DLM_REQCID as i32;
/// Native `EX_DLM_SPACE` constant.
pub const EX_DLM_SPACE: i32 = raw::NDRX_RS_EX_DLM_SPACE as i32;
/// Native `EX_DLM_DATA_BLOB` constant.
pub const EX_DLM_DATA_BLOB: i32 = raw::NDRX_RS_EX_DLM_DATA_BLOB as i32;
/// Native `EX_DLM_CURDATA_BLOB` constant.
pub const EX_DLM_CURDATA_BLOB: i32 = raw::NDRX_RS_EX_DLM_CURDATA_BLOB as i32;
/// Native `EX_DLM_SEQNO` constant.
pub const EX_DLM_SEQNO: i32 = raw::NDRX_RS_EX_DLM_SEQNO as i32;
/// Native `EX_DLM_SEQNO_TSEC` constant.
pub const EX_DLM_SEQNO_TSEC: i32 = raw::NDRX_RS_EX_DLM_SEQNO_TSEC as i32;
/// Native `EX_DLM_SEQNO_TUSEC` constant.
pub const EX_DLM_SEQNO_TUSEC: i32 = raw::NDRX_RS_EX_DLM_SEQNO_TUSEC as i32;
/// Native `EX_DLM_RVAL1` constant.
pub const EX_DLM_RVAL1: i32 = raw::NDRX_RS_EX_DLM_RVAL1 as i32;
/// Native `EX_DLM_LOCK_MODE` constant.
pub const EX_DLM_LOCK_MODE: i32 = raw::NDRX_RS_EX_DLM_LOCK_MODE as i32;
/// Native `EX_DLM_KEYTYP` constant.
pub const EX_DLM_KEYTYP: i32 = raw::NDRX_RS_EX_DLM_KEYTYP as i32;
/// Native `EX_DLM_WAIT_TIME` constant.
pub const EX_DLM_WAIT_TIME: i32 = raw::NDRX_RS_EX_DLM_WAIT_TIME as i32;
/// Native `EX_DLM_EVENT` constant.
pub const EX_DLM_EVENT: i32 = raw::NDRX_RS_EX_DLM_EVENT as i32;
/// Native `EX_DLM_EXPIRY_USEC` constant.
pub const EX_DLM_EXPIRY_USEC: i32 = raw::NDRX_RS_EX_DLM_EXPIRY_USEC as i32;
/// Native `EX_DLM_ADDDATA` constant.
pub const EX_DLM_ADDDATA: i32 = raw::NDRX_RS_EX_DLM_ADDDATA as i32;
/// Native `EX_DLM_CURKEY` constant.
pub const EX_DLM_CURKEY: i32 = raw::NDRX_RS_EX_DLM_CURKEY as i32;
/// Native `EX_DLM_INCONCLUSIVE` constant.
pub const EX_DLM_INCONCLUSIVE: i32 = raw::NDRX_RS_EX_DLM_INCONCLUSIVE as i32;
/// Native `EX_DLM_OPFLAGS` constant.
pub const EX_DLM_OPFLAGS: i32 = raw::NDRX_RS_EX_DLM_OPFLAGS as i32;

// Validate the native C string and UTF-8 at compile time.
const fn native_text(bytes: &'static [u8]) -> &'static str {
    let text = match std::ffi::CStr::from_bytes_with_nul(bytes) {
        Ok(text) => text,
        Err(_) => panic!("DLM constant must be a NUL-terminated C string"),
    };
    match std::str::from_utf8(text.to_bytes()) {
        Ok(text) => text,
        Err(_) => panic!("DLM constant must contain valid UTF-8"),
    }
}
/// Native `NDRX_DLM_LM_NULL` text.
pub const NDRX_DLM_LM_NULL: &str = native_text(raw::NDRX_DLM_LM_NULL);
/// Native `NDRX_DLM_LM_CONCURRENT_READ` text.
pub const NDRX_DLM_LM_CONCURRENT_READ: &str = native_text(raw::NDRX_DLM_LM_CONCURRENT_READ);
/// Native `NDRX_DLM_LM_CONCURRENT_WRITE` text.
pub const NDRX_DLM_LM_CONCURRENT_WRITE: &str = native_text(raw::NDRX_DLM_LM_CONCURRENT_WRITE);
/// Native `NDRX_DLM_LM_PROTECTED_READ` text.
pub const NDRX_DLM_LM_PROTECTED_READ: &str = native_text(raw::NDRX_DLM_LM_PROTECTED_READ);
/// Native `NDRX_DLM_LM_PROTECTED_WRITE` text.
pub const NDRX_DLM_LM_PROTECTED_WRITE: &str = native_text(raw::NDRX_DLM_LM_PROTECTED_WRITE);
/// Native `NDRX_DLM_LM_EXCLUSIVE` text.
pub const NDRX_DLM_LM_EXCLUSIVE: &str = native_text(raw::NDRX_DLM_LM_EXCLUSIVE);
/// Native `NDRX_DLM_CMD_LOCK` text.
pub const NDRX_DLM_CMD_LOCK: &str = native_text(raw::NDRX_DLM_CMD_LOCK);
/// Native `NDRX_DLM_CMD_UNLOCK` text.
pub const NDRX_DLM_CMD_UNLOCK: &str = native_text(raw::NDRX_DLM_CMD_UNLOCK);
/// Native `NDRX_DLM_CMD_ISLOCKED` text.
pub const NDRX_DLM_CMD_ISLOCKED: &str = native_text(raw::NDRX_DLM_CMD_ISLOCKED);
/// Native `NDRX_DLM_CMD_SET` text.
pub const NDRX_DLM_CMD_SET: &str = native_text(raw::NDRX_DLM_CMD_SET);
/// Native `NDRX_DLM_CMD_CAS` text.
pub const NDRX_DLM_CMD_CAS: &str = native_text(raw::NDRX_DLM_CMD_CAS);
/// Native `NDRX_DLM_CMD_GET` text.
pub const NDRX_DLM_CMD_GET: &str = native_text(raw::NDRX_DLM_CMD_GET);
/// Native `NDRX_DLM_CMD_DEL` text.
pub const NDRX_DLM_CMD_DEL: &str = native_text(raw::NDRX_DLM_CMD_DEL);
/// Native `NDRX_DLM_CMD_RENAME` text.
pub const NDRX_DLM_CMD_RENAME: &str = native_text(raw::NDRX_DLM_CMD_RENAME);
/// Native `NDRX_DLM_CMD_EXISTS` text.
pub const NDRX_DLM_CMD_EXISTS: &str = native_text(raw::NDRX_DLM_CMD_EXISTS);
/// Native `NDRX_DLM_CMD_DROPDB` text.
pub const NDRX_DLM_CMD_DROPDB: &str = native_text(raw::NDRX_DLM_CMD_DROPDB);
/// Native `NDRX_DLM_CMD_EXPIRELOCK` text.
pub const NDRX_DLM_CMD_EXPIRELOCK: &str = native_text(raw::NDRX_DLM_CMD_EXPIRELOCK);
/// Native `NDRX_DLM_CMD_FENCELOCK` text.
pub const NDRX_DLM_CMD_FENCELOCK: &str = native_text(raw::NDRX_DLM_CMD_FENCELOCK);
/// Native `NDRX_DLM_CMD_EXPIREDATA` text.
pub const NDRX_DLM_CMD_EXPIREDATA: &str = native_text(raw::NDRX_DLM_CMD_EXPIREDATA);
/// Native `NDRX_DLM_OP_DLMCMD` text.
pub const NDRX_DLM_OP_DLMCMD: &str = native_text(raw::NDRX_DLM_OP_DLMCMD);
/// Native `NDRX_DLM_OP_CANCEL` text.
pub const NDRX_DLM_OP_CANCEL: &str = native_text(raw::NDRX_DLM_OP_CANCEL);
/// Native `NDRX_DLM_OP_LSSTORE` text.
pub const NDRX_DLM_OP_LSSTORE: &str = native_text(raw::NDRX_DLM_OP_LSSTORE);
/// Native `NDRX_DLM_OP_ADDNODE` text.
pub const NDRX_DLM_OP_ADDNODE: &str = native_text(raw::NDRX_DLM_OP_ADDNODE);
/// Native `NDRX_DLM_OP_RMNODE` text.
pub const NDRX_DLM_OP_RMNODE: &str = native_text(raw::NDRX_DLM_OP_RMNODE);
/// Native `NDRX_DLM_OP_XFER` text.
pub const NDRX_DLM_OP_XFER: &str = native_text(raw::NDRX_DLM_OP_XFER);
/// Native `NDRX_DLM_OP_FENCEOK` text.
pub const NDRX_DLM_OP_FENCEOK: &str = native_text(raw::NDRX_DLM_OP_FENCEOK);
/// Native `NDRX_DLM_OP_DLMINIT` text.
pub const NDRX_DLM_OP_DLMINIT: &str = native_text(raw::NDRX_DLM_OP_DLMINIT);
/// Native `NDRX_DLM_OP_COMPACT` text.
pub const NDRX_DLM_OP_COMPACT: &str = native_text(raw::NDRX_DLM_OP_COMPACT);
/// Native `NDRX_DLM_OP_T_DLM` text.
pub const NDRX_DLM_OP_T_DLM: &str = native_text(raw::NDRX_DLM_OP_T_DLM);
/// Native `NDRX_DLM_FENCE_ST_SCH` text.
pub const NDRX_DLM_FENCE_ST_SCH: &str = native_text(raw::NDRX_DLM_FENCE_ST_SCH);
/// Native `NDRX_DLM_FENCE_ST_ATT` text.
pub const NDRX_DLM_FENCE_ST_ATT: &str = native_text(raw::NDRX_DLM_FENCE_ST_ATT);
/// Native `NDRX_DLM_FENCE_ST_EXE` text.
pub const NDRX_DLM_FENCE_ST_EXE: &str = native_text(raw::NDRX_DLM_FENCE_ST_EXE);
/// Native `NDRX_DLM_FENCE_ST_EXD` text.
pub const NDRX_DLM_FENCE_ST_EXD: &str = native_text(raw::NDRX_DLM_FENCE_ST_EXD);
/// Native `NDRX_DLM_FENCE_ST_FAI` text.
pub const NDRX_DLM_FENCE_ST_FAI: &str = native_text(raw::NDRX_DLM_FENCE_ST_FAI);
/// Native `NDRX_DLM_FENCE_ST_STL` text.
pub const NDRX_DLM_FENCE_ST_STL: &str = native_text(raw::NDRX_DLM_FENCE_ST_STL);
/// Native `NDRX_DLM_FENCE_ST_FOK` text.
pub const NDRX_DLM_FENCE_ST_FOK: &str = native_text(raw::NDRX_DLM_FENCE_ST_FOK);
/// Native `NDRX_DLM_FENCE_TY_INF` text.
pub const NDRX_DLM_FENCE_TY_INF: &str = native_text(raw::NDRX_DLM_FENCE_TY_INF);
/// Native `NDRX_DLM_FENCE_TY_LOC` text.
pub const NDRX_DLM_FENCE_TY_LOC: &str = native_text(raw::NDRX_DLM_FENCE_TY_LOC);
/// Native `NDRX_DLM_FENCE_TY_GLB` text.
pub const NDRX_DLM_FENCE_TY_GLB: &str = native_text(raw::NDRX_DLM_FENCE_TY_GLB);
/// Native `NDRX_DLM_NODE_FENCE_EV` text.
pub const NDRX_DLM_NODE_FENCE_EV: &str = native_text(raw::NDRX_DLM_NODE_FENCE_EV);
/// Native `NDRX_DLM_MEMBERSHIP_EV` text.
pub const NDRX_DLM_MEMBERSHIP_EV: &str = native_text(raw::NDRX_DLM_MEMBERSHIP_EV);
/// Native `NDRX_DLM_STATE_EV` text.
pub const NDRX_DLM_STATE_EV: &str = native_text(raw::NDRX_DLM_STATE_EV);
/// Native `NDRX_DLM_XFER_EV` text.
pub const NDRX_DLM_XFER_EV: &str = native_text(raw::NDRX_DLM_XFER_EV);
